### ISSUE TITLE
Please include direct links to xpi and crx files

### ISSUE THREAD

**Issue by FredThompsonII** [Dalimil/Web-Design-Pirate#1]
Web Design Pirate is coming up 404 at mozilla addons site.
Please include direct links to xpi and crx files.

**Comment by Dalimil** [comment]
I know, they took it down because of the unsafe-eval I had in my CSP.
Links to [XPI here](https://github.com/Dalimil/Web-Design-Pirate/tree/master/firefox-xpi)

**Comment by Dalimil** [comment]
@FredThompsonII It's been officially released here: https://addons.mozilla.org/en-CA/firefox/addon/web-design-pirate-for-devtools/
