### ISSUE TITLE
Please use Releases section in Github for Firefox and an update.json

### ISSUE THREAD

**Issue by andreicristianpetcu** [Dalimil/Web-Design-Pirate#2]
Hi,

Pretty cool extension!

If you put your XPI file in the releases section like [this example](https://github.com/andreicristianpetcu/google_translate_this/releases) people will be able to install it with [one click](https://github.com/andreicristianpetcu/google_translate_this/releases/download/v1.2.7/google_translate_this_page-1.2.7-an.fx.xpi).

If you also add an [update.json](https://github.com/andreicristianpetcu/google_translate_this/blob/master/updates.json) to your [manifest.json](https://github.com/andreicristianpetcu/google_translate_this/blob/68a81a022240a64c294057079da3ef9df89f7c8f/manifest.json#L44) then you will use the Firefox automatic update system to ship updates.

Thank you for your extension!

**Comment by Dalimil** [comment]
Done.

**Comment by andreicristianpetcu** [comment]
The link in readme points to 404
Firefox Add-on: XPI package

**Comment by andreicristianpetcu** [comment]
Can you please put the signed XPI file rather than the zip? If you put the XPI file it will be a one click install.

**Comment by Dalimil** [comment]
@andreicristianpetcu It's been officially released here: https://addons.mozilla.org/en-CA/firefox/addon/web-design-pirate-for-devtools/
