### ISSUE TITLE
Responsive layouts don't give correct rendering

### ISSUE THREAD

**Issue by emmastone9** [Dalimil/Web-Design-Pirate#3]
Go to any RWD website: https://digg.com

Select the top nav bar class, the one that contains header with breadcrumb. 

The preview window doesn't show the mobile version of the nav-bar, it shows the desktop version. 

Setting the user-agent for mobile kinda works, though the layout is still messy and not as clean as desktop version.

**Comment by Dalimil** [comment]
Yes, because that's by design. You load the extension in desktop so it gives desktop version. If the website had responsive layout for different window size it would resize, but I think they are loading something else for mobile devices altogether.
