### ISSUE TITLE
issue with firefox

### ISSUE THREAD

**Issue by Bodagous** [Dalimil/Web-Design-Pirate#4]
thanks for the extension. 
it works well on chrome but not firefox 57.0.2

**Comment by hpvd** [comment]
hmmm maybe this is related to https://github.com/Dalimil/Web-Design-Pirate/issues/5
I do not know the exact version of FF when it stoppped working for me, but since 57 was released August 17, I'm pretty sure it works some month longer for me (I'm on beta channel an use always latest beta)

**Comment by Dalimil** [comment]
Fixed in v1.2

**Comment by Dalimil** [comment]
@Bodagous It's been released here: https://addons.mozilla.org/en-CA/firefox/addon/web-design-pirate-for-devtools/
