### ISSUE TITLE
not working anymore in FF 59b12+ / 59final / 60b3

### ISSUE THREAD

**Issue by hpvd** [Dalimil/Web-Design-Pirate#5]
not working anymore in FF 59b12

was working greatt before!

message: file not found
please see attachment.

reinstallation doesn't help

![2018-02-27_14h50_48](https://user-images.githubusercontent.com/5681880/36732371-d899e318-1bcd-11e8-96f0-e701e4816028.png)

**Comment by Dalimil** [comment]
Thanks for reporting this

**Comment by hpvd** [comment]
just to keep you update (since it could be caused by temporally problem of firefox beta):
still the same with 59b14

**Comment by hpvd** [comment]
just to make report complete:
wasn't a problem of a beta version.
Not working in FF 59 final (released)
and not in 60b3

**Comment by kraigmustard** [comment]
I couldn't get this to work in FF 55.0b9 56.0b1, I would get the cross domain error or something.

FF 60 (I think) and 61.0b3 would produce the above errors for me.

**Comment by hpvd** [comment]
sadly, this awesome extension seems to be dead for firefox users forever now
(no sign of rebirth with FF62 (b4))

**Comment by Anthony-Gaudino** [comment]
> sadly, this awesome extension seems to be dead for firefox users forever now
> (no sign of rebirth with FF62 (b4))

Still doesn't work in FF69

**Comment by LoneDev6** [comment]
Still not working

**Comment by Heath123** [comment]
It happens because `src` is in the URL twice @Dalimil

**Comment by Dalimil** [comment]
@hpvd @LoneDev6 @Anthony-Gaudino @Heath123 Download the v1.2 version from the releases section, it's been fixed.

**Comment by hpvd** [comment]
awesome . Many thanks working on this!
Just gave it a try:
downloaded Main.zip and tried to install it from file:
"Could not be installed. File seems to be damaged."
FF 85b4

edit:
which FF version work fine for you?
Did you directly try to install from file (FF is fine to accept .zip)?

**Comment by hpvd** [comment]
@Dalimil reopen?

**Comment by hpvd** [comment]
same message for latest release (v1.5):

"Could not be installed. File seems to be damaged."
FF 85b4

![2021-01-02_21h48_34](https://user-images.githubusercontent.com/5681880/103466330-728ead00-4d44-11eb-94ef-441bb371475a.png)

**Comment by Dalimil** [comment]
@hpvd Yes, it cannot be installed directly in Firefox. You need to wait for the Firefox extension store submission I made.

**Comment by hpvd** [comment]
ah just saw the readme.md was changed and has an explanation:

> Firefox Add-on: Custom signed XPI is no longer supported, I'm trying to get the extension approved in the store. Meanwhile, you can use it as a local debug addon in Firefox.

**Comment by Dalimil** [comment]
@hpvd @Anthony-Gaudino @Heath123 @kraigmustard @LoneDev6 It's been released for Firefox officially: https://addons.mozilla.org/en-CA/firefox/addon/web-design-pirate-for-devtools/
