### ISSUE TITLE
Not working on particular site.

### ISSUE THREAD

**Issue by christoshrousis** [Dalimil/Web-Design-Pirate#6]
Hey,

Have the following "CSS input" error:

{"isException":true,"value":"DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules\n    at slice.call.map (<anonymous>:2:65)\n    at Array.map (<anonymous>)\n    at getStyleSheets (<anonymous>:2:48)\n    at <anonymous>:8:5"}

for the following site:
http://spirit.com.au/

Will try my best to see if I can create a PR, if you could give me a hint in the meantime that would be sweet.

**Comment by christoshrousis** [comment]
Actually how do I even contribute to this? hahaha

**Comment by christoshrousis** [comment]
So I was testing my bugfix locally, I figured out how to upload to chrome, and then I got a new error on the same site!!!! This time the error was in the right hand side box and it said the following:

An error occurred. Error: SyntaxError: Unexpected token < in JSON at position 0

I can't give this a shot now, might try visit later tonight.

**Comment by sswari** [comment]
Hi Christoshrousis,
Have you had any luck with the JSON Issue?

**Comment by christoshrousis** [comment]
I fixed it like this PR: https://github.com/Dalimil/Web-Design-Pirate/pull/7

**Comment by sswari** [comment]
Ok, not a pro at this by any stretch, just some coding several years ago. So please excuse ignorance.

I believe I have your patch installed, as the changes showing on lines 13 and 14 match the lines on the page you referenced.

What I am getting in the CSS results is "An error occurred. Error: SyntaxError: Unexpected token < in JSON at position 0"  on a few pages.

**Comment by Dalimil** [comment]
It's been fixed in v1.3 for Chrome
